# Generated by Django 5.2.3 on 2025-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_usercredits_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
