# Generated by Django 5.2.3 on 2025-07-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_facebook_social_platform_remove_card_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='client',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='location',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
