# Generated by Django 5.2.3 on 2025-07-18 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_label_subscriber_subscriberlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.label'),
        ),
    ]
