# Generated by Django 5.2.3 on 2025-07-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscriber_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set(),
        ),
    ]
