# Generated by Django 5.2.3 on 2025-07-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0002_rename_facebook_social_platform_remove_card_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.page'),
        ),
    ]
