# Generated by Django 5.2.3 on 2025-07-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
